name: Install

on:
  push:
    branches:
      - 'main'  # All branches
      - 'master'
      - 'develop'
      - 'release/**'
  pull_request:
    branches:
      - 'main'  # All branches
      - 'master'
      - 'develop'
      - 'release/**'

env:
  CTEST_OUTPUT_ON_FAILURE: 1
  # Using Conan for dependency management

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Conan
        run: |
          python -m pip install --upgrade pip
          pip install conan

      - name: Detect Conan profile
        run: conan profile detect --force

      - name: Cache Conan packages
        uses: actions/cache@v4
        with:
          path: ~/.conan2
          key: ${{ runner.os }}-conan-${{ hashFiles('**/conanfile.txt') }}
          restore-keys: |
            ${{ runner.os }}-conan-

      - name: build and install library
        run: |
          mkdir -p build
          cd build
          conan install .. --output-folder=. --build=missing
          cmake -S .. -B . -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake
          sudo cmake --build . --target install
          cd ..
          rm -rf build

      - name: configure
        run: |
          mkdir -p build
          cd build
          conan install ../test --output-folder=. --build=missing
          cmake -S ../test -B . -DTEST_INSTALLED_VERSION=1 -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake

      - name: build
        run: cmake --build build --config Debug -j4

      - name: test
        run: |
          cd build
          ctest --build-config Debug
