name: Style

on:
  push:
    branches:
      - 'main'
      - 'master'  # All branches
      - 'develop'
      - 'release/**'
  pull_request:
    branches:
      - 'main'  # All branches
      - 'master'
      - 'develop'
      - 'release/**'

env:
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Conan
        run: |
          python -m pip install --upgrade pip
          pip install conan

      - name: Detect Conan profile
        run: conan profile detect --force

      - name: Cache Conan packages
        uses: actions/cache@v4
        with:
          path: ~/.conan2
          key: ${{ runner.os }}-conan-${{ hashFiles('**/conanfile.txt') }}
          restore-keys: |
            ${{ runner.os }}-conan-

      - name: configure
        run: |
          mkdir -p build
          cd build
          conan install ../test --output-folder=. --build=missing
          cmake -S ../test -B . -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake

      - name: check style
        run: cmake --build build --target check-format
